name: Build tools
on:
  push:
    tags:
      - 'v*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Build UI
      run: cd ui && npm install . && npx quasar build

    - name: Install bindata
      run: GO111MODULE=off go get -u -v github.com/go-bindata/go-bindata/...

    - name: Build assets
      run: cd assets && $(go env GOPATH)/bin/go-bindata -pkg assets -prefix ../ui/dist/spa -fs ../ui/dist/spa/...

    - uses: azure/docker-login@v1
      with:
        username: 'reddec'
        password: ${{ secrets.DOCKERIO_PASSWORD }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_BINTRAY_SECRET: ${{ secrets.UPLOAD_BINTRAY_SECRET }}